from django.urls import path
from . import views

app_name = 'fakture'

urlpatterns = [
    path('', views.pocetna_stranica, name='index'),
    path('pdf/<str:pk>/', views.pdf_generator, name='pdf1'),
    path('kreiranje-fakture/', views.KreirajFakturu.as_view(), name='kreiraj-fakturu'),
    path('kreiranje-fakture/<int:pk>/prodaja/', views.KreirajFakturuProdaja.as_view(), name='faktura-prodaja'),
    path('kreiranje-fakture/prodaja/<int:pk>/', views.faktura_skica_gotova, name='faktura-skica'),
    path('kreiranje-fakture/prodaja/<int:pk>/detalji/', views.ProdajaDetalji.as_view(), name='prodaja-detalji'),
    path('kreiranje-fakture/prodaja/<int:pk>/izmjena/', views.ProdajaIzmjena.as_view(), name='prodaja-izmjena'),
    path('kreiranje-fakture/prodaja/<int:pk>/brisanje/', views.ProdajaBrisanje.as_view(), name='prodaja-brisanje'),
    path('kreiranje-fakture/<int:pk>/izmjena/', views.FakturaUpdate.as_view(), name='faktura-izmjena'),
    path('kreiranje-fakture/izmjena/<int:pk>/prodaja/', views.ProdajaGlavnaUpdate.as_view(), name='faktura-prodaja-izmjena'),
    path('lista_faktura/', views.FaktureLista.as_view(), name='lista_fakturi'),
    path('kupci/', views.KupciLista.as_view(), name='lista-kupci'),
    path('lista_faktura/<int:pk>/', views.FaktureDetail.as_view(), name='faktura-detalji'),
    path('kupci/novi-kupac/', views.KupacNovi.as_view(), name='kupac-novi'),
    path('kupac/<int:pk>/', views.KupacDetalji.as_view(), name='kupac-detalji'),
    path('kupac/<int:pk>/update/', views.KupacUpdate.as_view(), name='kupac-update'),
    path('base-nativ/', views.base, name='base-nativ'),
    path('valute/', views.KreirajValute.as_view(), name='kreiraj-valutu'),
    path('<int:pk>/', views.ValuteUpdate.as_view(), name='valute_update'),
    path('pozicije-lista/', views.PozicijaLista.as_view(), name='pozicije-lista'),
    #path('usluge-lista/kreiraj-uslugu/', views.UslugaKreiraj.as_view(), name='usluge-kreiraj'),
    #path('usluge-lista/kreiraj-uslugu/<int:pk>/update/', views.UslugaUpdate.as_view(), name='usluge-update'),
    path('pozicija/kreiraj/', views.PozicijaKreiraj.as_view(), name='pozicije-kreiraj'),
    path('pozicija/kreiraj/<int:pk>/update/', views.PozicijaUpdate.as_view(), name='pozicija-update'),
    path('lista_faktura/godine/<str:year>/', views.faktura_po_godinama, name='fakture_po_godinama'),
    path('lista_ponuda/', views.PonudaLista.as_view(), name='ponuda-lista'),
    path('lista_ponuda/<int:pk>/', views.PonudaDetail.as_view(), name='ponuda-detalji'),
    path('ponuda-create/', views.KreirajPonudu.as_view(), name='ponuda-create'),
    path('ponuda-create/<int:pk>/ponuda-prodaja/', views.KreirajPonuduProdaja.as_view(), name='ponuda-prodaja'),
    path('ponuda-create/ponuda-prodaja/<int:pk>/detalji/', views.ProdajaPonudaDetalji.as_view(), name='ponuda-prodaja-detalji'),
    path('ponuda-create/prodaja-ponuda/<int:pk>/', views.ponuda_skica_gotova, name='ponuda-skica'),
    path('ponuda-pdf/<str:pk>/', views.pdf_generator_ponuda, name='ponuda-pdf'),
    path('ponuda-create/<int:pk>/izmjena/', views.PonudaUpdate.as_view(), name='ponuda-izmjena'),
    path('ponuda-create/prodaja/<int:pk>/brisanje/', views.PonudaProdajaBrisanje.as_view(), name='ponuda-prodaja-brisanje'),
    path('ponuda-create/prodaja/<int:pk>/izmjena/', views.PonudaProdajaIzmjena.as_view(), name='ponuda-prodaja-izmjena'),
    path('usluge-lista/<str:year>/', views.ponude_po_godinama, name='ponude_po_godinama'),
    path('pdf-lista/', views.MojiPDF.as_view(), name='lista-pdf-files'),
    path('placene-fakture/', views.pregled_placenih_faktura_godine, name='placene-fakture-godine'),
    path('placene-fakture/<int:year>/', views.pregled_placenih_faktura, name='placene-fakture'),
    path('placene-fakture/update/<int:pk>/', views.FakturePlaceneUpdate.as_view(), name='placene-fakture-update'),
    path('excel/<int:year>/', views.export_users_xls, name='export-excel'),
    path('ponuda-u-fakturu/<int:pk>', views.ponuda_u_fakturu, name='ponuda-u-fakturu'),
    path('realizacija-ponuda/<int:pk>/', views.ponuda_storno, name='ponuda-storniranje'),
]